// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cumsum_colrev
arma::mat cumsum_colrev(NumericMatrix m);
RcppExport SEXP _intasymmRcppArma_cumsum_colrev(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(cumsum_colrev(m));
    return rcpp_result_gen;
END_RCPP
}
// cvpl
arma::mat cvpl(NumericMatrix theta, NumericMatrix censor);
RcppExport SEXP _intasymmRcppArma_cvpl(SEXP thetaSEXP, SEXP censorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type censor(censorSEXP);
    rcpp_result_gen = Rcpp::wrap(cvpl(theta, censor));
    return rcpp_result_gen;
END_RCPP
}
// cumsum_col
NumericMatrix cumsum_col(NumericMatrix m);
RcppExport SEXP _intasymmRcppArma_cumsum_col(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(cumsum_col(m));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_intasymmRcppArma_cumsum_colrev", (DL_FUNC) &_intasymmRcppArma_cumsum_colrev, 1},
    {"_intasymmRcppArma_cvpl", (DL_FUNC) &_intasymmRcppArma_cvpl, 2},
    {"_intasymmRcppArma_cumsum_col", (DL_FUNC) &_intasymmRcppArma_cumsum_col, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_intasymmRcppArma(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
