# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cumsum_colrev <- function(m) {
    .Call(`_intasymmRcppArma_cumsum_colrev`, m)
}

cvpl <- function(theta, censor) {
    .Call(`_intasymmRcppArma_cvpl`, theta, censor)
}

cumsum_col <- function(m) {
    .Call(`_intasymmRcppArma_cumsum_col`, m)
}

